"""
Numerical Solver for 1D SU(2) Gauge-Coupled Fokker-Planck Systems
=============================================================================
Companion codebase for research manuscript on multi-state stochastic dynamics.

System Overview:
  This module implements a numerical solver for a system of N = 3 Fokker-Planck
  equations coupled through a non-Abelian SU(2) gauge field theoretical framework.
  It models multi-state stochastic dynamics where distinct probability density 
  sectors P_a(x,t) (for a = 1, 2, 3) exchange probability through non-local spatial 
  and temporal interactions.

Algorithmic Core (Non-Oscillatory Forward-in-Time, NFT):
  1. Multidimensional Positive Definite Advection Transport Algorithm (MPDATA)
     [Smolarkiewicz 1984, 1998, 2006]:
     A two-step non-oscillatory advection solver (Donor-Cell upwinding + antidiffusive
     pseudo-velocity correction) that eliminates numerical diffusion while maintaining
     strict positive-definiteness.
  2. Inverted Operator-Splitting Framework [Strang 1968, Kärcher 2003, Prusa 2008]:
     - Phase I (Pre-conditioning): Solves physical diffusion R^n_{a,i} alongside non-local 
       spatial interaction terms Gamma and time-memory integral accumulators Theta at linear O(g)
       and quadratic O(g^2) gauge coupling orders, yielding an intermediate density P_tilde.
     - Phase II (Conservative Transport): Advances the pre-conditioned density P_tilde 
       using the MPDATA advective drift operator.
  3. Conservation & Physical Constraints:
     Enforces strict non-negativity (clipping numerical underflows) and re-normalizes total 
     integrated probability across all N=3 sectors: int_Omega sum_a P_a(x,t) dx = N.
"""

import numpy as np
from scipy.integrate import trapezoid


def mpdata_1d(P_old, velocity, dx, dt):
    """
    Solves the 1D pure conservative advection equation:
        partial_t P(x,t) + partial_x [ v(x) * P(x,t) ] = 0

    using the two-step MPDATA scheme (Non-Oscillatory Forward-in-Time, NFT)
    [Smolarkiewicz 1984, 1998; Kärcher 2003]:

    - Step 1 (Donor-Cell Upwind): Computes first-order transport, which inherently 
      introduces an implicit numerical diffusion term K_num = 0.5 * (|v|*dx - dt*v^2).
    - Step 2 (Antidiffusive Step): Calculates a corrective pseudo-velocity field 
      v_corr = (K_num / dx) * (d P / P) to subtract the artificial numerical 
      diffusion while preserving strict non-negativity and profile shapes.
    """
    N = len(P_old)
    P_passo1 = P_old.copy()
    P_finale = P_old.copy()

    # -------------------------------------------------------------------------
    # STEP 1: First-order Upwind Advection (Donor-Cell Step)
    # -------------------------------------------------------------------------
    F_upwind = np.zeros(N)
    for i in range(N - 1):
        # Cell interface average velocity v_{i + 1/2}
        v_interfaccia = 0.5 * (velocity[i] + velocity[i+1])

        # Upwind flux evaluation based on advection direction
        if v_interfaccia >= 0:
            F_upwind[i] = v_interfaccia * P_old[i]
        else:
            F_upwind[i] = v_interfaccia * P_old[i+1]

    # Intermediate state update after Donor-Cell advection
    for i in range(1, N - 1):
        P_passo1[i] = P_old[i] - (dt / dx) * (F_upwind[i] - F_upwind[i-1])

    # -------------------------------------------------------------------------
    # STEP 2: Antidiffusive Velocity Correction (Truncation Error Cancellation)
    # -------------------------------------------------------------------------
    F_antidiff = np.zeros(N)
    for i in range(N - 1):
        v_interfaccia = 0.5 * (velocity[i] + velocity[i+1])
        abs_v = abs(v_interfaccia)

        # Artificial numerical diffusion coefficient K_num generated by upwinding
        diff_numerica = 0.5 * (abs_v * dx - dt * v_interfaccia**2)

        # Relative logarithmic gradient estimation: (dP/dx) / P
        denominatore = P_passo1[i] + P_passo1[i+1] + 1e-12  # Regularization floor
        pendenza = (P_passo1[i+1] - P_passo1[i]) / denominatore

        # Antidiffusive pseudo-velocity field
        v_correttiva = (diff_numerica / dx) * pendenza

        # Antidiffusive flux calculation via donor-cell structure
        if v_correttiva >= 0:
            F_antidiff[i] = v_correttiva * P_passo1[i]
        else:
            F_antidiff[i] = v_correttiva * P_passo1[i+1]

    # Final correction step yielding the sharp, non-oscillatory distribution
    for i in range(1, N - 1):
        P_finale[i] = P_passo1[i] - (dt / dx) * (F_antidiff[i] - F_antidiff[i-1])

    return P_finale


def init_gauss_1d(x_grid, cx, width, dx):
    """
    Generates an initial 1D Gaussian probability density profile:
        P(x) = exp(-((x - cx)^2) / width)
    normalized so that the integrated probability across the domain equals 1 (int P dx = 1).
    """
    p = np.exp(-((x_grid - cx)**2) / width)
    return p / (np.sum(p) * dx)


def run_simulation():
    """
    Executes the time integration loop for the N=3 SU(2) gauge-coupled Fokker-Planck system.
    Solves 3 coupled stochastic sectors using an Inverted Operator-Splitting method 
    combined with MPDATA advective transport.

    Requires no input arguments.

    Returns
    -------
    dict
        Contains spatial grid x_vals, initial/final states (Ps_init, Ps_final),
        full temporal history STORIA_Ps, and diagnostic force balance records.
    """
    save_history = True
    verbose = True

    # =========================================================================
    # 1. DISCRETIZATION PARAMETERS & GAUGE COUPLING STRENGTH
    # =========================================================================
    Nx = 100                          # Spatial grid resolution N_x
    x_vals = np.linspace(0, 10, Nx)   # Spatial domain Omega = [0, 10]
    dx = x_vals[1] - x_vals[0]        # Grid spacing Delta x

    dt = 0.0004                       # Time step Delta t (CFL stability bound)
    t_final = 1.0                     # Total simulation domain duration t_{final} (seconds)
    steps = int(t_final / dt)         # Total discrete time steps

    # Global non-Abelian SU(2) gauge coupling strength g and quadratic order g^2
    g = 0.2
    g2 = g ** 2

    # =========================================================================
    # 2. PHYSICAL SECTORS & DRIFT/DIFFUSION PARAMETER SPECIFICATIONS
    # =========================================================================
    # Transport properties for 3 Ornstein-Uhlenbeck stochastic sectors:
    # - Linear drift velocity fields: v_a(x) = alpha_a * x
    drift_funcs = [
        lambda x: 0.3 * x,   # Drift velocity coefficient for Sector 1
        lambda x: 0.5 * x,   # Drift velocity coefficient for Sector 2
        lambda x: 0.7 * x    # Drift velocity coefficient for Sector 3
    ]
    # - Constant diffusion coefficients: D_a
    diff_coeffs = [0.10, 0.15, 0.20]
    N_dist = len(drift_funcs)  # N = 3 probability sectors (SU(2) triplet)

    # Initial Condition: Identical Gaussian profiles centered at x = 5.0
    Ps = [init_gauss_1d(x_vals, 5.0, 1.0, dx) for _ in range(N_dist)]
    Ps_init = [p.copy() for p in Ps]

    # Historical state buffers (at time step t_n - dt) for backward temporal derivatives
    Ps_old = [p.copy() for p in Ps]
    Flussi_old = [np.zeros(Nx) for _ in range(N_dist)]

    # Time-memory integral accumulators Theta_g(t_n) and Theta_{g^2}(t_n)
    # initialized to zero at t = 0
    accumulatori_temporali_g = [np.zeros(Nx) for _ in range(N_dist)]
    accumulatori_temporali_g2 = [np.zeros(Nx) for _ in range(N_dist)]

    STORIA_Ps = [[p.copy() for p in Ps]] if save_history else []

    if verbose:
        print("=" * 83)
        print("NUMERICAL INTEGRATION INITIALIZED (SU(2) GAUGE-COUPLED FOKKER-PLANCK)")
        print(f"Domain: x in [0, 10], Nx = {Nx}, dt = {dt}, Total Steps = {steps}")
        print(f"Gauge Coupling Parameter: g = {g} (g^2 = {g2:.4f})")
        print("=" * 83)
        print(f"{'STEP':<6} | {'SECT':<5} | {'DIFF':<6} | {'SP(g)':<6} | {'TM(g)':<6} | {'SP(g2)':<6} | {'TM(g2)':<6} | {'DRIFT':<6}")
        print("-" * 83)

    # =========================================================================
    # 3. TIME INTEGRATION LOOP (Core Operator-Splitting Algorithm)
    # =========================================================================
    # Executes the two-stage fractional-step integration sequence:
    #   Step 3a: Calculates current physical current J_a(x,t) and density gradients dP/dx.
    #   Step 3b: Evaluates temporal derivatives (dP/dt, dJ/dt) via backward finite differences.
    #   Step 3c: Computes non-local spatial (Gamma) and time-memory (Theta) gauge source terms.
    #   Step 3d: Phase I (Pre-conditioning with physical diffusion & gauge source terms)
    #            followed by Phase II (Conservative advective transport via MPDATA).
    #   Step 3e: Physical constraint enforcement (Non-negativity clipping & Global normalization).
    # =========================================================================
    for n in range(steps):

        # ---------------------------------------------------------------------
        # 3a. Current Physical Current J_a(x,t) and Density Gradient Evaluation
        # ---------------------------------------------------------------------
        # Spatial gradient of density: dP_a / dx
        gradiente_P = [np.gradient(p, dx) for p in Ps]

        # Total local physical current: J_a(x) = v_a(x) * P_a(x) - D_a * (dP_a / dx)
        Flussi_correnti = []
        for a in range(N_dist):
            v_griglia = drift_funcs[a](x_vals)
            D = diff_coeffs[a]
            flusso_a = v_griglia * Ps[a] - D * gradiente_P[a]
            Flussi_correnti.append(flusso_a)

        # ---------------------------------------------------------------------
        # 3b. Temporal Derivatives Approximation (dP/dt and dJ/dt)
        # ---------------------------------------------------------------------
        # Approximated via backward finite differences between step n and step n-1
        dt_P = []
        dt_Flusso = []
        for a in range(N_dist):
            if n == 0:
                # Boundary initialization at first time level t_0
                dt_P.append(np.zeros(Nx))
                dt_Flusso.append(np.zeros(Nx))
            else:
                dt_P.append((Ps[a] - Ps_old[a]) / dt)
                dt_Flusso.append((Flussi_correnti[a] - Flussi_old[a]) / dt)

        # Update historical state vectors for iteration n + 1
        Ps_old = [p.copy() for p in Ps]
        Flussi_old = [f.copy() for f in Flussi_correnti]

        # ---------------------------------------------------------------------
        # 3c. Evaluation of Non-Local Gauge Source Terms O(g) and O(g^2)
        # ---------------------------------------------------------------------
        gammas_space_g = np.zeros(N_dist)
        gammas_space_g2 = np.zeros(N_dist)

        for a in range(N_dist):
            # Cyclic sector permutations (A, B) for Levi-Civita tensor epsilon_{abc}
            habitA = (a + 1) % N_dist
            habitB = (a + 2) % N_dist

            P_A, P_B = Ps[habitA], Ps[habitB]
            grad_P_A, grad_P_B = gradiente_P[habitA], gradiente_P[habitB]
            J_A, J_B = Flussi_correnti[habitA], Flussi_correnti[habitB]
            dt_P_A, dt_P_B = dt_P[habitA], dt_P[habitB]
            dt_F_A, dt_F_B = dt_Flusso[habitA], dt_Flusso[habitB]

            # --- (i) Linear Spatial Gauge Coupling Term Gamma_{a, space, g} ---
            blocco_spazio_avanti_g   = P_A * grad_P_B - 2 * P_A * dt_F_B + dt_P_B * J_A
            blocco_spazio_indietro_g = P_B * grad_P_A - 2 * P_B * dt_F_A + dt_P_A * J_B
            integrando_spaziale_g = blocco_spazio_avanti_g - blocco_spazio_indietro_g
            # Discrete trapezoidal integration across spatial domain Omega
            gammas_space_g[a] = trapezoid(integrando_spaziale_g, x_vals)

            # --- (ii) Quadratic Spatial Gauge Coupling Term Gamma_{a, space, g^2} ---
            blocco_spazio_A_g2 = P_A * (Ps[a] * J_A - P_A * Flussi_correnti[a])
            blocco_spazio_B_g2 = P_B * (Ps[a] * J_B - P_B * Flussi_correnti[a])
            integrando_spaziale_g2 = blocco_spazio_A_g2 + blocco_spazio_B_g2
            gammas_space_g2[a] = trapezoid(integrando_spaziale_g2, x_vals)

            # --- (iii) Linear Temporal Memory Term Theta_{a, i, g}^{time}(t_n) ---
            grad_F_A = np.gradient(J_A, dx)
            grad_F_B = np.gradient(J_B, dx)

            blocco_tempo_avanti_g   = J_A * dt_F_B + grad_F_B * P_A - 2 * J_A * grad_P_B
            blocco_tempo_indietro_g = J_B * dt_F_A + grad_F_A * P_B - 2 * J_B * grad_P_A
            integrando_time_g = blocco_tempo_avanti_g - blocco_tempo_indietro_g
            # Boundary zeroing to prevent unphysical memory accumulations at grid edges
            integrando_time_g[0] = integrando_time_g[1] = integrando_time_g[-2] = integrando_time_g[-1] = 0.0

            # Recursive accumulation of time-memory integral: Theta(t_n) = Theta(t_{n-1}) + dt * integrand
            if n > 0:
                accumulatori_temporali_g[a] += dt * integrando_time_g

            # --- (iv) Quadratic Temporal Memory Term Theta_{a, i, g^2}^{time}(t_n) ---
            blocco_tempo_A_g2 = J_A * (P_A * Flussi_correnti[a] - Ps[a] * J_A)
            blocco_tempo_B_g2 = J_B * (P_B * Flussi_correnti[a] - Ps[a] * J_B)
            integrando_time_g2 = blocco_tempo_A_g2 + blocco_tempo_B_g2
            integrando_time_g2[0] = integrando_time_g2[1] = integrando_time_g2[-2] = integrando_time_g2[-1] = 0.0

            if n > 0:
                accumulatori_temporali_g2[a] += dt * integrando_time_g2

        P_intermediate = [p.copy() for p in Ps]
        matrice_pesi = []

        # ---------------------------------------------------------------------
        # 3d. Inverted Operator-Splitting Step (Phases I & II)
        # ---------------------------------------------------------------------
        for a in range(N_dist):
            D = diff_coeffs[a]
            Pc = Ps[a]
            v_griglia = drift_funcs[a](x_vals)

            # --- PHASE I: Pre-conditioning Step ---
            # 2nd-order central difference discretization of physical diffusion: d^2 P / dx^2
            d2p_dx2 = (Pc[2:] - 2 * Pc[1:-1] + Pc[:-2]) / dx**2

            # Incremental updates over time step dt
            delta_diff      = dt * (D * d2p_dx2)                                  # Physical diffusion
            delta_spazio_g  = dt * (g * gammas_space_g[a])                        # Linear spatial gauge source
            delta_tempo_g   = dt * (g * accumulatori_temporali_g[a][1:-1])        # Linear time-memory gauge source
            delta_spazio_g2 = dt * (g2 * gammas_space_g2[a])                      # Quadratic spatial gauge source
            delta_tempo_g2  = dt * (g2 * accumulatori_temporali_g2[a][1:-1])       # Quadratic time-memory gauge source

            # Update density to generate intermediate pre-conditioned profile P_tilde
            P_intermediate[a][1:-1] += (delta_diff + delta_spazio_g + delta_tempo_g + delta_spazio_g2 + delta_tempo_g2)

            # Local balance boundary conditions on intermediate profile (P_tilde[0] = P_tilde[1])
            P_intermediate[a][0] = P_intermediate[a][1]
            P_intermediate[a][-1] = P_intermediate[a][-2]

            # --- PHASE II: Conservative Transport Step ---
            # Apply MPDATA advection solver to pre-conditioned state P_tilde
            P_final_sector = mpdata_1d(P_intermediate[a], v_griglia, dx, dt)

            # Boundary condition enforcement on updated state
            P_final_sector[0] = P_final_sector[1]
            P_final_sector[-1] = P_final_sector[-2]

            # --- Diagnostic Force Balance Breakdown ---
            f_drift     = np.mean(np.abs(P_final_sector - P_intermediate[a]))
            f_diff      = np.mean(np.abs(delta_diff))
            f_spazio_g  = np.mean(np.abs(delta_spazio_g))
            f_tempo_g   = np.mean(np.abs(delta_tempo_g))
            f_spazio_g2 = np.mean(np.abs(delta_spazio_g2))
            f_tempo_g2  = np.mean(np.abs(delta_tempo_g2))

            totale_forze = f_drift + f_diff + f_spazio_g + f_tempo_g + f_spazio_g2 + f_tempo_g2 + 1e-12

            matrice_pesi.append((
                (f_diff / totale_forze) * 100,
                (f_spazio_g / totale_forze) * 100,
                (f_tempo_g / totale_forze) * 100,
                (f_spazio_g2 / totale_forze) * 100,
                (f_tempo_g2 / totale_forze) * 100,
                (f_drift / totale_forze) * 100
            ))

            Ps[a] = P_final_sector.copy()

        # Print diagnostic force breakdown table every 100 iterations
        if verbose and (n % 100 == 0):
            for a in range(N_dist):
                step_str = f"{n:<6}" if a == 0 else "      "
                print(f"{step_str} | P{a+1:<4} | {matrice_pesi[a][0]:>5.1f}% | {matrice_pesi[a][1]:>5.1f}% | {matrice_pesi[a][2]:>5.1f}% | {matrice_pesi[a][3]:>5.1f}% | {matrice_pesi[a][4]:>5.1f}% | {matrice_pesi[a][5]:>5.1f}%")
            print("-" * 83)

        # ---------------------------------------------------------------------
        # 3e. Physical Constraint Enforcement (Positivity & Global Normalization)
        # ---------------------------------------------------------------------
        # (1) Non-negativity constraint: clipping below-threshold numerical underflows
        Ps = [np.clip(p, 1e-12, None) for p in Ps]

        # (2) Global probability conservation scaling across all N=3 coupled sectors:
        #     sum_{a=1}^3 int_{Omega} P_a(x,t) dx = N = 3
        total_prob = np.sum(Ps) * dx
        Ps = [p * (float(N_dist) / total_prob) for p in Ps]

        if save_history:
            STORIA_Ps.append([p.copy() for p in Ps])

    if verbose:
        print("=" * 83)
        print("SIMULATION COMPLETED SUCCESSFULLY.")
        print("=" * 83)

    return {
        'x_vals': x_vals,
        'Ps_init': Ps_init,
        'Ps_final': Ps,
        'STORIA_Ps': STORIA_Ps,
        'dt': dt,
        't_final': t_final,
        'N_dist': N_dist
    }


if __name__ == "__main__":
    results = run_simulation()
